name: livescore_kf
description: "Real-time sports scoreboard app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  go_router: ^15.1.2
  get_it: ^8.0.3
  web_socket_channel: ^3.0.2
  equatable: ^2.0.7
  http: ^1.2.2
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.13
  go_router_builder: ^2.7.1

flutter:
  uses-material-design: true
